Repository Earth-mas/Earth-mas_client, pull requests merged in 2022-07, with the labels that each got.

#224 fix: logout error & profile image & mypage address inputs
  src/components/commons/inputs/Input01.tsx
  src/components/commons/profile/profile.tsx
  src/components/units/myPage/user/profile/updateAddress.tsx
  src/hooks/useSetUser.tsx
Labels: 🐞 BugFix

#225 Bugfix: axiosInstance 오류 수정
  src/components/commons/upload/02/Upload02.tsx
Labels: 🐞 BugFix

#227 Design: [#226] main image 변경
  public/images/mainImg/main-activity.jpeg
  public/images/mainImg/main-market.jpg
  public/images/mainImg/main-support.jpg
  src/assets/images/mainImg/main1.jpg
  src/assets/images/mainImg/main2.jpg
  src/assets/images/mainImg/main3.jpg
  src/pages/index.tsx
Labels: 🎨 Html&css

#229 [Fix] oauth
  src/components/units/myPage/market/MyPageMarket.tsx
  src/components/units/myPage/market/bought/bought.tsx
  src/components/units/myPage/market/like/like.tsx
  src/components/units/myPage/market/sell/sell.tsx
  src/components/units/myPage/user/profile/updatePassword.tsx
  src/hooks/useSetUser.tsx
  src/index.js
Labels: 🐞 BugFix

#230 [setting] dockerfile
  Dockerfile
  docker-compose.yaml
  src/commons/utils/axiosInstance.tsx
Labels: ⚙ Setting

#231 fix: logout
  src/components/commons/layout/header/index.tsx
Labels: 🐞 BugFix
